### ISSUE TITLE
Scroll only when the whole element show which affect mobile

### ISSUE THREAD

**Issue by ghost** [crazychicken/t-scroll#4]
The scroll effect only happens when the whole div or element show, which sometime would affect long element, but which is pretty bad for mobile as the effect might come in only too late. 

Is there a way to trigger the effect as soon as the element is in the view instead of when the whole element is in the view?

**Comment by crazychicken** [comment]
Hi @damarusama , thank you using t-scroll, Actually there is an option - [t-position](http://t-scroll.com/t-position.html) which may help you!
Please, tell me if there is anything i could help with this problem!

**Comment by ghost** [comment]
Thanks - that work'ish.  The t-position is calculated from the bottom of the div right? On a mobile device the div height changes  quite considerably. What would make sense in that situation? If the height was calculated from the top it would be simpler to code, so that we wouldn't need to change the t-position per device.

**Comment by crazychicken** [comment]
Hi @damarusama, thank you using t-scroll!
I understood your problem. this is a necessary option for t-scroll. i will update in the next version (v1.1.0)
Please tell to free contact me, if you need any further information.

**Comment by crazychicken** [comment]
Hi @damarusama, i have just updated v1.1.0.
You can view it:
Demo: http://t-scroll.com/t-position.html
&&
Docs: http://t-scroll.com/documents.html
Please tell to free contact me, if you need any further information.

**Comment by ghost** [comment]
Wow! thanks I'll update my code to reflect this change!
