### ISSUE TITLE
Speed of animation

### ISSUE THREAD

**Issue by polarpixel** [crazychicken/t-scroll#6]
Hi,

is it possible to set the speed of the animation?
I want to animate two elements with a different speed.

Thanks for your help,
Peter.

**Comment by crazychicken** [comment]
Hi @polarpixel ,
Thank you using t-scroll, Actually there is an option - [t-duration](http://t-scroll.com/t-duration.html) which may help you!
You need call two function:

```
<script type="text/javascript">
    Tu.t_scroll({
      't_element': '.classname_1 .zoomIn',
      't_duration': 0.1 // speed here
    })
    Tu.t_scroll({
      't_element': '.classname_2 .zoomIn',
      't_duration': 0.2 // speed here
    })
</script>
```
Please tell to free contact me, if you need any further information.
